# Generated by Django 2.1.3 on 2018-12-12 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appfiafia', '0002_remove_notification_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='uploader',
        ),
        migrations.AddField(
            model_name='notification',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appfiafia.Group'),
            preserve_default=False,
        ),
    ]
