# Generated by Django 2.1.3 on 2018-12-12 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appfiafia', '0003_auto_20181212_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='uploader',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
